class Config:
    FOG_COVERAGE_RADIUS = 200
    CLOUD_COVERAGE_RADIUS = 1000

    CLOUD_NODE_COUNT = 1

    TIMESLOT_LENGTH = 1
    SIMULATION_DURATION = 99

    PACKET_COST_PER_METER = 0.005
    TASK_COST_PER_METER = 0.001

    CLOUD_POWER = 100
    FOG_POWER = 30
