class Config:
    FOG_COVERAGE_RADIUS = 100
    CLOUD_COVERAGE_RADIUS = 1000
    ZONE_COVERAGE_RADIUS = 200

    ZONE_COUNT = 10
    FOG_NODE_COUNT = 100
    USER_NODE_COUNT = 100
    CLOUD_NODE_COUNT = 1

    TIMESLOT_LENGTH = 1
    SIMULATION_DURATION = 100

    PACKET_COST_PER_METER = 0.0001
    TASK_COST_PER_METER = 0.001
