class Config:
    FOG_COVERAGE_RADIUS = 200
    CLOUD_COVERAGE_RADIUS = 100

    CLOUD_NODE_COUNT = 1

    TIMESLOT_LENGTH = 1
    SIMULATION_DURATION = 99

    PACKET_COST_PER_METER = 0.01
    TASK_COST_PER_METER = 0.001
